### ISSUE TITLE
When trying the attack methods, they don't want to work.

### ISSUE THREAD

**Issue by CaptainNox** [Leeon123/Aoyama#2]
So, everything works (setting up the CNC, connecting the bots to it etc...) but when I want to try the attack methods they don't work.
The commands go through, but when I try to hit a dstat it doesn't show any network traffic, also with tcpdump.
Do you guys maybe know what the problem could be?

Kind regards.

**Comment by Kali95739** [comment]
How did you connect to bots to your server I cant figure it out it seems like it doesn't want to connect for me
