### ISSUE TITLE
CPU usages

### ISSUE THREAD

**Issue by ghost** [Leeon123/Aoyama#4]
I'm not too sure whether this has occurred with anyone else, but the cpu usage is insanely high. I've tested on both 3.8 and 3.5, i'm getting 100% usage on my linux box, and 30-50% on my home device, have you noticed this as well, or is this somehow an issue on my end?
This project is really nice tho i'm not going to lie

**Comment by Leeon123** [comment]
What was the script you tested? cnc.py or client.py

**Comment by ghost** [comment]
This was using the cnc, I'm thinking it was the threading, then again not 100% sure

**Comment by Leeon123** [comment]
ok i'll check it out later

**Comment by Leeon123** [comment]
Now it should be fixed
