### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by CYBRIU** [Leeon123/Aoyama#5]
So, when i connect to it on putty it works but when i type !anything it says network error how do i  fix it?

**Comment by Leeon123** [comment]
Did you set all the things correct?

**Comment by CYBRIU** [comment]
i had no errors

**Comment by Leeon123** [comment]
I mean the settings, tell me about ur command to run the cnc and ur cnc ip

**Comment by Leeon123** [comment]
Now it should be fixed, please download the latest cnc.py
