### ISSUE TITLE
Nice source.

### ISSUE THREAD

**Issue by ghost** [Leeon123/Aoyama#9]
If you need some more attack vectors (Like VSE, or ACK). I have 45 methods, and all of them are python.
Send me a message if you want them.

**Comment by frosniqq** [comment]
> If you need some more attack vectors (Like VSE, or ACK). I have 45 methods, and all of them are python.
> Send me a message if you want them.

go

**Comment by Egida** [comment]
> If you need some more attack vectors (Like VSE, or ACK). I have 45 methods, and all of them are python.
> Send me a message if you want them.

go

**Comment by ghost** [comment]
done lol, might push some more later

**Comment by Leeon123** [comment]
Good luck.
